# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f705a910f075446f2812128600eb9cc4c99dcb306fe66dbf2b1f709e15432b1c751feb88f7618a86d91d6df93f55655ced5708539928873cb75ff6734e04544
  devise_jwt_secret_key: 9f22810bc74a75fb1611f6a9c43ab882499b8912079afe6e13a2db074f0be0cc64ef2c0d7d7f91e0d8585f04c86662f8f4c88fd628cb673d18c060904f76d9fd

test:
  secret_key_base: 95b10cc76a594ad87e8076d912f74f47bf535aedde4189d5f9f111c658fbb56b34c0e1b55f62b389462e99f5c36a2fc8e378a5e900ff7e94934fdc0fe2056bd8
  devise_jwt_secret_key: ce7bb72ca720cd39211dd4effd7d4cfdbe5a492789dac64ae2e56d5f31c3cae424776837659a1af1085e0ad43b377dc234d7d1e07efdf51995fa387ecd38c5c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  devise_jwt_secret_key: <%= ENV["DEVISE_JWT_SECRET_KEY"] %>
